export { default as simpleObjects } from "./simple";
export { default as createObjectDungeon } from "./create-objects-dungeon";
export { default as removeObjectDungeon } from "./remove-object-dungeon";
export { default as putObjectDungeon } from "./put-object-dungeon";
export { aggregateObjects } from "./aggregate-objects";
export { default as TYPE_OBJECT } from "./type-object";
export { createCorpse, createStairsUp, createStairsDown } from "./specials";
export * from "./weapons";
export * from "./simple";
export * from "./ammo";
