export default {
  simple: "object/simple",
  meleeWeapon: "object/melee-weapon",
  distanceWeapon: "object/distance-bow",
  ammo: "object/ammo",
  ammunition: "object/ammunition",
  armor: "object/armor",
  potion: "object/potion",
  chest: "object/chest",
  corpse: "object/corpse",
  key: "object/key",
  door: "object/door",
  stairsUp: "object/stairs-up",
  stairsDown: "object/stairs-down",
};
