# C'est la partie obligatoire contenant l'étape de construction pour gatsby
language: node_js
node_js:
  - '12'
cache:
  yarn: true
  directories:
    - public
    - .cache
script:
  - yarn build # Générer des fichiers HTML statiques

# Voici la partie magique
deploy:
  # Utiliser le processus de déploiement des pages Github
  provider: pages
  skip-cleanup: true
  # Répertoire où se trouvent les fichiers générés
  local_dir: public
  # Github security/auth token
  github-token: $GITHUB_TOKEN
  # Conserve les anciens fichiers/constructions des déploiements précédents
  keep-history: true
  # La branche Git sur laquelle on souhaite déployer (master, gh-pages, foo...)
  target_branch: gh-pages
  on:
    # Quelle branche déclenchera le déploiement
    branch: master